name: flutter_application_3
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^5.4.4
  collection: ^1.17.1
  cupertino_icons: ^1.0.8
  curved_labeled_navigation_bar: ^2.0.5
  easy_localization: ^3.0.7
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  firebase_database: ^11.2.0
  firebase_in_app_messaging: ^0.8.1
  firebase_messaging: ^15.2.0
  firebase_storage: ^12.3.5
  flutter_bloc: ^8.1.6
  flutter_plugin_android_lifecycle: ^2.0.6
  flutter_story_presenter: ^1.0.0
  font_awesome_flutter: ^10.5.0
  google_fonts: ^6.2.1
  hero_animation: ^1.1.4
  http: ^1.2.2
  image_picker: ^1.1.2
  lottie: ^3.0.0
  page_transition: ^2.1.0
  provider: ^6.0.0
  shared_preferences: ^2.3.2
  share_plus: ^10.1.3
  video_player: ^2.9.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/lottie/
    - assets/lang/en.json
    - assets/lang/ar.json
    - assets/lang/fr.json
    - assets/lang/de.json
